[project]
    name = "Model Training"
    description = "Model training repository"
    company = "Oguzhan"
    author = "Mert Oğuzhan"

[logger]
    filepath="./logs/model_training.log"
    rotation="50MB"

[LlamaTrain]
    dataset_path = "./dataset/dataset.csv" 
    test_size = 0.15
    random_state = 55
    model_name = "NousResearch/Llama-2-7b-chat-hf"
    trust_remote_code = true
    padding_side = "right"
    load_in_4bit = true 
    bnb_4bit_quant_type = "nf4" 
    bnb_4bit_use_double_quant = false 
    device_map = "balanced" 
    lora_alpha = 8
    lora_rank = 32
    lora_dropout = 0.15
    bias = "none"
    task_type = "CAUSAL_LM"
    output_dir = "./output_with_metrics"
    num_train_epochs = 8
    per_device_train_batch_size = 1
    gradient_accumulation_steps = 1
    learning_rate = 0.00002
    weight_decay = 0.001
    logging_steps = 15
    fp16 = true
    bf16 = false
    report_to = "none"
    dataset_text_field = "question" # dataset'te hangi column baz alınarak çıktı ona göre üretilsin.

[LlamaInference]

    model_name = "./output_with_metrics/checkpoint-11752"
    task = "text-generation"
    max_length = 200
    prompt = "What does the company do?"

[FastApiServer]
    [FastapiServer]
    host = "0.0.0.0"
    port = 8000
    reload = true
    log_level = "debug"
